[*]
capslock_l.space = toggle(mark_l)
capslock_l.h = backspace
capslock_l.d = delete
capslock_l.a = home
capslock_l.e = end
capslock_l.p = up
capslock_l.n = down
capslock_l.f = right
capslock_l.b = left
capslock_l.v = pagedown
capslock_l.m = enter
capslock_l.w = C-x
capslock_l.y = C-v
capslock_l.k = macro(S-end C-x)
capslock_l.s = macro(C-f C-g)
capslock_l.g = escape
capslock_l./ = C-z
capslock_l.x = oneshot(ctrlx_l)

escape = oneshot(alt)

alt.f = C-right
alt.b = C-left
alt.v = pageup
alt.w = C-c
alt.d = macro(C-S-right C-x)

shift+alt.comma = C-home
shift+alt.dot = C-end

capslock_l+mark_l.a = S-home
capslock_l+mark_l.e = S-end
capslock_l+mark_l.p = S-up
capslock_l+mark_l.n = S-down
capslock_l+mark_l.f = S-right
capslock_l+mark_l.b = S-left
capslock_l+mark_l.w = togglem(mark_l, C-x)
capslock_l+mark_l.g = togglem(mark_l, escape)

alt+mark_l.f = C-S-right
alt+mark_l.b = C-S-left
alt+mark_l.w = togglem(mark_l, C-c)

capslock_l+ctrlx_l.f = C-o
capslock_l+ctrlx_l.s = C-s
capslock_l+ctrlx_l.c = A-f4

[org-kde-konsole]
capslock_l.space = C-space
capslock_l.h = C-h
capslock_l.d = C-d
capslock_l.a = C-a
capslock_l.e = C-e
capslock_l.p = C-p
capslock_l.n = C-n
capslock_l.f = C-f
capslock_l.b = C-b
capslock_l.v = C-v
capslock_l.m = C-m
capslock_l.w = C-w
capslock_l.y = C-y
capslock_l.k = C-k
capslock_l.s = C-s
capslock_l.g = C-g
capslock_l./ = C-/
capslock_l.x = C-x

escape = escape

alt.f = A-f
alt.b = A-b
alt.v = A-v
alt.w = A-w
alt.d = A-d

shift+alt.comma = S-A-comma 
shift+alt.dot = S-A-dot

capslock_l+mark_l.a = C-a
capslock_l+mark_l.e = C-e
capslock_l+mark_l.p = C-p
capslock_l+mark_l.n = C-n
capslock_l+mark_l.f = C-f
capslock_l+mark_l.b = C-b
capslock_l+mark_l.w = C-w
capslock_l+mark_l.g = C-g

alt+mark_l.f = A-f
alt+mark_l.b = A-b
alt+mark_l.w = A-w

capslock_l+ctrlx_l.f = C-f
capslock_l+ctrlx_l.s = C-s
capslock_l+ctrlx_l.c = C-c

[emacs]
capslock_l.space = C-space
capslock_l.h = C-h
capslock_l.d = C-d
capslock_l.a = C-a
capslock_l.e = C-e
capslock_l.p = C-p
capslock_l.n = C-n
capslock_l.f = C-f
capslock_l.b = C-b
capslock_l.v = C-v
capslock_l.m = C-m
capslock_l.w = C-w
capslock_l.y = C-y
capslock_l.k = C-k
capslock_l.s = C-s
capslock_l.g = C-g
capslock_l./ = C-/
capslock_l.x = C-x

escape = escape

alt.f = A-f
alt.b = A-b
alt.v = A-v
alt.w = A-w
alt.d = A-d

shift+alt.comma = S-A-comma 
shift+alt.dot = S-A-dot

capslock_l+mark_l.a = C-a
capslock_l+mark_l.e = C-e
capslock_l+mark_l.p = C-p
capslock_l+mark_l.n = C-n
capslock_l+mark_l.f = C-f
capslock_l+mark_l.b = C-b
capslock_l+mark_l.w = C-w
capslock_l+mark_l.g = C-g

alt+mark_l.f = A-f
alt+mark_l.b = A-b
alt+mark_l.w = A-w

capslock_l+ctrlx_l.f = C-f
capslock_l+ctrlx_l.s = C-s
capslock_l+ctrlx_l.c = C-c

[virt-manager]
capslock_l.space = C-space
capslock_l.h = C-h
capslock_l.d = C-d
capslock_l.a = C-a
capslock_l.e = C-e
capslock_l.p = C-p
capslock_l.n = C-n
capslock_l.f = C-f
capslock_l.b = C-b
capslock_l.v = C-v
capslock_l.m = C-m
capslock_l.w = C-w
capslock_l.y = C-y
capslock_l.k = C-k
capslock_l.s = C-s
capslock_l.g = C-g
capslock_l./ = C-/
capslock_l.x = C-x

escape = escape

alt.f = A-f
alt.b = A-b
alt.v = A-v
alt.w = A-w
alt.d = A-d

shift+alt.comma = S-A-comma 
shift+alt.dot = S-A-dot

capslock_l+mark_l.a = C-a
capslock_l+mark_l.e = C-e
capslock_l+mark_l.p = C-p
capslock_l+mark_l.n = C-n
capslock_l+mark_l.f = C-f
capslock_l+mark_l.b = C-b
capslock_l+mark_l.w = C-w
capslock_l+mark_l.g = C-g

alt+mark_l.f = A-f
alt+mark_l.b = A-b
alt+mark_l.w = A-w

capslock_l+ctrlx_l.f = C-f
capslock_l+ctrlx_l.s = C-s
capslock_l+ctrlx_l.c = C-c
