[ids]
*

[global]
overload_tap_timeout = 250

[main]
capslock = overload(capslock_l, oneshot(capslock_t))
rightshift = rightshift
rightcontrol = rightcontrol
#sysrq = lettermod(sysrq_l, sysrq, 150, 250)

[capslock_l:C]
[capslock_t]
capslock = layer(capslock_w)
[capslock_w:C]

[shift+alt]

[mark_l]
[capslock_l+mark_l]
[alt+mark_l]

[ctrlx_l]
[capslock_l+ctrlx_l]

[esc_l]

#[sysrq_l]
