[ids]
*

[global]
overload_tap_timeout = 250

[main]
capslock = overload(capslock_l, oneshot(capslock_t))
leftalt = overload(alt_l, oneshot(alt_t))
rightshift = rightshift
rightcontrol = rightcontrol
#sysrq = lettermod(sysrq_l, sysrq, 150, 250)

[capslock_l:C]
[capslock_t]
capslock = layer(capslock_w)
[capslock_w:C]

[shift+capslock_l]

[alt_l:A]
[alt_t]
leftalt = layer(alt_w)
[alt_w:A]

[shift+alt_l]

[alt_l+capslock_l]

[mark_l]
[capslock_l+mark_l]
[alt_l+mark_l]

[ctrlx_l]
[capslock_l+ctrlx_l]

[esc_l:A]

#[sysrq_l]
